language: node_js
node_js:
  - 0.10
  - 0.12
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
before_install:
  - echo 'deb http://deb.debian.org/debian bookworm-backports main contrib non-free'
    > sources.list
  - sudo cp sources.list /etc/apt/sources.list
  - sudo cat /etc/apt/sources.list
  - sudo rm -rf /etc/apt/sources.list.d/*
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 0E98404D386FA1D9
    6ED0E7B82643E131
  - sudo apt-get update
  - npm config set strict-ssl=false
  - npm config set registry 
    https://:2019-03-16T15%3A26%3A17.735Z@time-machines-npm-direct-download.sealsecurity.io/
dist: trusty
